input: /home/ubuntu/temp/spec-kit
output: /home/ubuntu/ai-ws/translate_cli/output/spec-kit
source_lang: en
target_lang: zh
ext: [md]
concurrency: 8
reserve_code: true
preserve_frontmatter: true
retry: 3
timeout: 60
backup: true
batch:
  chars: 16000
  segments: 6
